language: node_js
node_js:
  - "stable"
services:
  - mongodb  
script:
  - npm test  
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: $HEROKU_API_NAME
